# Generated by Django 2.0 on 2020-02-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Django blog', max_length=100, verbose_name='网站名称')),
                ('site_description', models.CharField(default='A new Django blog', max_length=1000, verbose_name='网站描述')),
                ('beian_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='备案号')),
                ('latest_article_count', models.PositiveIntegerField(default=5, verbose_name='最新文章数目')),
                ('sidebar_hot_article_count', models.PositiveIntegerField(default=5, verbose_name='侧边栏最热文章数目')),
                ('show_sidebar_html', models.BooleanField(default=True, verbose_name='是否显示侧边栏html')),
                ('show_sidebar_hot_article', models.BooleanField(default=True, verbose_name='是否显示侧边栏最热文章')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('is_nav', models.BooleanField(default=False, verbose_name='是否为导航')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_index', models.PositiveIntegerField(blank=True, default=1, verbose_name='展示顺序数字大的靠前')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最热文章')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='如果展示的部署HTML类型，不可为空', max_length=500, verbose_name='内容')),
                ('status', models.PositiveIntegerField(choices=[(1, '展示'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
            },
        ),
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称')),
                ('display_type', models.PositiveIntegerField(choices=[(1, '超链接'), (3, '我的博客'), (2, '归档'), (4, '管理'), (5, '首页')], default=1, verbose_name='类型')),
                ('show_type', models.BooleanField(default=True, verbose_name='是否显示')),
                ('content', models.CharField(blank=True, max_length=512, null=True, verbose_name='内容,超链接必须有内容')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='链接')),
            ],
            options={
                'verbose_name': '顶部导航按钮',
                'verbose_name_plural': '顶部导航按钮',
            },
        ),
    ]
