# Generated by Django 3.0.3 on 2020-02-21 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '我的博客'), (3, '归档'), (4, '管理'), (5, '首页')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='链接,报错的时候'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='name',
            field=models.CharField(default=1, max_length=20, verbose_name='名称'),
            preserve_default=False,
        ),
    ]
