# Generated by Django 3.0.3 on 2020-02-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0002_auto_20200224_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '我的博客'), (3, '管理')], default=1, verbose_name='类型'),
        ),
    ]
