# Generated by Django 3.0.3 on 2020-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0002_auto_20200221_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='content',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='链接到的地址,超链接必须有内容'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '我的博客'), (3, '管理'), (4, '首页')], default=1, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='link',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='链接,admin里save_model方法自动保存'),
        ),
    ]
