# Generated by Django 3.0.3 on 2020-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0003_auto_20200228_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='content',
            field=models.CharField(blank=True, help_text='如果展示的是HTML类型，不可为空', max_length=500, verbose_name='内容'),
        ),
    ]
