# Generated by Django 3.0.3 on 2020-02-22 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0003_auto_20200222_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='display_index',
            field=models.PositiveIntegerField(default=1, verbose_name='数字越大显示越靠前'),
        ),
    ]
