# Generated by Django 3.0.3 on 2020-02-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0004_topbar_display_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='index_post_count',
            field=models.PositiveIntegerField(default=6, verbose_name='首页展示文章条数'),
        ),
    ]
