# Generated by Django 3.0.3 on 2020-02-21 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200221_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='post',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='blog',
        ),
    ]
