# Generated by Django 3.0.3 on 2020-02-22 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeconfig', '0004_topbar_display_index'),
        ('blog', '0007_post_site_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='site_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homeconfig.Category', verbose_name='网站分类'),
        ),
    ]
