# Generated by Django 3.0.3 on 2020-02-24 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='名称')),
                ('display_type', models.PositiveIntegerField(choices=[(1, '超链接'), (2, '归档'), (3, '管理'), (4, '首页'), (5, '我的博客'), (6, '友链'), (7, '关于')], default=1, verbose_name='类型')),
                ('show_type', models.BooleanField(default=True, verbose_name='是否显示')),
                ('display_index', models.PositiveIntegerField(default=1, verbose_name='数字越大越靠前')),
                ('content', models.CharField(blank=True, max_length=512, null=True, verbose_name='内容,超链接必须有内容')),
                ('link', models.CharField(blank=True, max_length=512, null=True, verbose_name='链接')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blog')),
            ],
            options={
                'verbose_name': '顶部导航按钮',
                'verbose_name_plural': '顶部导航按钮',
            },
        ),
        migrations.CreateModel(
            name='SideBar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_index', models.PositiveIntegerField(blank=True, default=1, verbose_name='展示顺序数字大的靠前')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('display_type', models.PositiveIntegerField(choices=[(1, 'HTML'), (2, '最新文章'), (3, '最热文章'), (4, '最近评论')], default=1, verbose_name='展示类型')),
                ('content', models.CharField(blank=True, help_text='如果展示的部署HTML类型，不可为空', max_length=500, verbose_name='内容')),
                ('status', models.PositiveIntegerField(choices=[(1, '展示'), (0, '隐藏')], default=1, verbose_name='状态')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者')),
            ],
            options={
                'verbose_name': '侧边栏',
                'verbose_name_plural': '侧边栏',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('href', models.URLField(verbose_name='链接')),
                ('status', models.PositiveIntegerField(choices=[(1, '正常'), (0, '删除')], default=1, verbose_name='状态')),
                ('weight', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, help_text='权重高展示顺序靠前', verbose_name='权重')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者')),
            ],
            options={
                'verbose_name': '友链',
                'verbose_name_plural': '友链',
            },
        ),
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Django blog', max_length=100, verbose_name='网站名称')),
                ('site_description', models.CharField(default='A new Django blog', max_length=1000, verbose_name='网站描述')),
                ('beian_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='备案号')),
                ('sidebar_latest_article_count', models.PositiveIntegerField(default=5, verbose_name='侧边栏最新文章数目')),
                ('sidebar_hot_article_count', models.PositiveIntegerField(default=5, verbose_name='侧边栏最热文章数目')),
                ('sidebar_comment_count', models.PositiveIntegerField(default=5, verbose_name='侧边栏评论数目')),
                ('show_sidebar_html', models.BooleanField(default=True, verbose_name='是否显示侧边栏html')),
                ('show_sidebar_comment', models.BooleanField(default=True, verbose_name='是否显示侧边栏评论')),
                ('show_sidebar_hot_article', models.BooleanField(default=True, verbose_name='是否显示侧边栏最热文章')),
                ('show_sidebar_latest_article', models.BooleanField(default=True, verbose_name='是否显示侧边栏最新文章')),
                ('index_post_count', models.PositiveIntegerField(default=8, verbose_name='首页文章展示数目')),
                ('archive_post_count', models.PositiveIntegerField(default=10, verbose_name='归档页面文章展示数目')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
