# Generated by Django 3.0.3 on 2020-02-21 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogsettings',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='link',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sidebar',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='topbar',
            name='owner',
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='link',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sidebar',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Blog', verbose_name='作者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topbar',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.Blog'),
            preserve_default=False,
        ),
    ]
