# Generated by Django 3.0.3 on 2020-02-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_auto_20200221_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '归档'), (3, '管理'), (4, '首页')], default=1, verbose_name='类型'),
        ),
    ]
