# Generated by Django 3.0.3 on 2020-02-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200225_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='show_sidebar_toc',
            field=models.BooleanField(default=True, verbose_name='是否显示文章侧边TOC'),
        ),
    ]
