# Generated by Django 3.0.3 on 2020-02-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_auto_20200222_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='display_index',
            field=models.PositiveIntegerField(default=1, verbose_name='数字越大越靠前'),
        ),
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '归档'), (3, '管理'), (4, '首页'), (5, '我的博客')], default=1, verbose_name='类型'),
        ),
    ]
