# Generated by Django 3.0.3 on 2020-02-26 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_auto_20200225_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sidebar',
            name='title',
            field=models.CharField(max_length=50, verbose_name='标题'),
        ),
    ]
