# Generated by Django 3.0.3 on 2020-02-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_auto_20200226_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='name',
            field=models.CharField(max_length=20, verbose_name='名称'),
        ),
    ]
