# Generated by Django 3.0.3 on 2020-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0007_auto_20200226_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='display_type',
            field=models.PositiveIntegerField(choices=[(1, '超链接'), (2, '归档'), (3, '管理'), (4, '博客园首页'), (5, '友链'), (6, '关于')], default=1, verbose_name='类型'),
        ),
    ]
