# Generated by Django 3.0.3 on 2020-02-26 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200224_2234'),
        ('config', '0008_auto_20200226_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.Blog')),
            ],
            options={
                'verbose_name': 'About页面',
                'verbose_name_plural': 'About页面',
            },
        ),
    ]
