# Generated by Django 3.0.3 on 2020-02-26 10:16

from django.db import migrations, models
import django.utils.timezone
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0009_aboutpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content',
            field=mdeditor.fields.MDTextField(default='', verbose_name='正文'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='阅读数'),
        ),
    ]
