# Generated by Django 3.0.3 on 2020-02-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0010_auto_20200226_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='uv',
            field=models.PositiveIntegerField(default=1, verbose_name='阅读数uv'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='pv',
            field=models.PositiveIntegerField(default=1, verbose_name='阅读数pv'),
        ),
    ]
