# Generated by Django 3.0.3 on 2020-02-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0012_auto_20200228_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topbar',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='名称'),
        ),
    ]
