# Generated by Django 3.0.3 on 2020-02-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='nickname',
            field=models.CharField(max_length=100, null=True, verbose_name='昵称'),
        ),
    ]
